#!/usr/bin/env python3
"""
N7_classify_19_37.py — classify the unclassified rigid primes N = 19 and
N = 37 (the reviewer's directive; note that 17 was already classified last
turn as Theorem K17 — the real gaps in the committed residual were 19 and
37), then re-measure the corpora with the augmented battery
P4 at {7, 13, 17, 19, 37}.

Classification method (K7-style, proof-grade):
  Lemma C5 (proved, general prime N) reduces the covering question to:
  4 multiplicative translates of S_h = {classes of 1..h} cover the class
  group C_m, m = (N-1)/2, cyclic of order m.  At both N = 19 and N = 37
  the class group is generated by cls(2) (verified in-script), so classes
  carry EXPONENTS in Z_m and translates become additive shifts:
  covering  <=>  the 4 exponents e_w (of X_w = class(w^{-1})) satisfy
  (e_w + S) union = Z_m, where S = exponents of S_h.
  Multiplying all four residues by a unit translates all exponents by a
  common constant, so covering depends only on the translate CLASS of the
  exponent multiset.  NOTE (self-caught presentation error, fixed): on the
  cyclic group Z_m, "contains 0" does NOT pin down a translate — every
  distinct element can be rotated to 0, so a 4-element class has up to 4
  contains-0 representatives.  The true class invariant is
  canon_class(E) = min over x in distinct(E) of sorted((e - x) mod m).
  Also: exponent negation is NOT a symmetry of the covering problem
  (B_{-w} = B_w since ||-wk|| = ||wk||); the classification is stated over
  translate classes only.  The classification is the explicit list of
  covering translate classes of Z_m — enumerated exhaustively over all
  C(m+2,3)-scale contains-0 multisets (each covering class therefore
  appears with ALL its representatives), cross-validated three ways
  (mask-level, set-level, predicate-level).

Checks performed before any augmented number is recorded:
  1. mask-level covering count == committed (64 at 19, 32 at 37);
  2. independent set-based capability recount agrees;
  3. every residue-level covering maps into the exponent classification;
     every classified covering canonical multiset is realized by residues;
  4. predicate (class-union < m) <=> mask non-covering, exhaustive over ALL
     unit 4-multisets at 19 (5,985) and 37 (82,251);
  5. orbit-list characterization <=> mask covering on the same enumeration;
  6. flag => certification sweeps (exhaustive at 19 and 37, plus the
     committed ranges).
"""
from math import gcd
from itertools import combinations, combinations_with_replacement
from collections import Counter
import random
import time

# EXTENDED P4 modulus set at T=6 (the battery change under measurement)
CLS_MODULI = {5: (7, 11, 13), 6: (7, 13, 17, 19, 37)}
RIGID_PRIMES = (7, 13, 17, 19, 37)

# ------------------------------------------------------------------ tables

def build_tables(N, T):
    full = (1 << N) - 1
    masks = [0] * N
    sizes = [0] * N
    orders = [0] * N
    invs = [False] * N
    for w in range(N):
        m = 0
        for k in range(N):
            r = (w * k) % N
            d = r if r <= N - r else N - r
            if T * d < N:
                m |= 1 << k
        masks[w] = m
        sizes[w] = bin(m).count('1')
        orders[w] = N // gcd(w, N)
        invs[w] = (w != 0) and gcd(w, N) == 1
    return dict(masks=masks, sizes=sizes, orders=orders, invs=invs, full=full)

def capable_units(N, tab, k):
    masks, full = tab['masks'], tab['full']
    units = [w for w in range(1, N) if tab['invs'][w]]
    covers = []
    m1 = masks[1]
    idx = list(range(len(units)))
    if k == 4:
        for i in idx:
            ma = m1 | masks[units[i]]
            for jj in idx[i:]:
                mb = ma | masks[units[jj]]
                for kk in idx[jj:]:
                    if mb | masks[units[kk]] == full:
                        covers.append((1, units[i], units[jj], units[kk]))
    return covers

def capable_setbased(N, T=6):
    units = [w for w in range(1, N) if gcd(w, N) == 1]

    def bad_set(w):
        return frozenset(k for k in range(N) if T * cls(w * k, N) < N)

    B = {w: bad_set(w) for w in units}
    B1 = B[1]
    full = frozenset(range(N))
    covers = []
    n = len(units)
    for i in range(n):
        sb = B1 | B[units[i]]
        for jj in range(i, n):
            sc = sb | B[units[jj]]
            for kk in range(jj, n):
                if sc | B[units[kk]] == full:
                    covers.append((1, units[i], units[jj], units[kk]))
    return covers

# ------------------------------------------------------------- class tools

def cls(x, N):
    r = x % N
    return r if r <= N - r else N - r

def cls_inv(w, N):
    return cls(pow(w, -1, N), N)

def flag_classification(N, rs, T):
    """P4 with the EXTENDED modulus set (19 and 37 added)."""
    if N not in CLS_MODULI[T]:
        return None
    h = (N - 1) // T
    m = (N - 1) // 2
    covered = set()
    for r in rs:
        X = cls_inv(r, N)
        for j in range(1, h + 1):
            covered.add(cls(X * j, N))
    return 'P4:cls%d' % N if len(covered) < m else None

def flag_D3(N, rs, n, T, invs):
    if not all(invs[r] for r in rs):
        return None
    pm = len({(r if r <= N - r else N - r) for r in rs})
    if pm > n - 2:
        return None
    h = (N - 1) // T
    if pm * (2 * h + 1) - (pm - 1) < N:
        return 'P5:D3'
    return None

def battery_flags(N, rs, n, T, tabs, capable, sigcap=None):
    tab = tabs[N]
    invs = tab['invs']
    fl = []
    for j in range(2, T + 1):
        if N % j == 0 and all(r % j for r in rs):
            fl.append('P1:jgon%d' % j)
            break
    allinv = all(invs[r] for r in rs)
    if allinv:
        f = flag_classification(N, rs, T)
        if f:
            fl.append(f)
    f = flag_D3(N, rs, n, T, invs)
    if f:
        fl.append(f)
    if sum(tab['sizes'][r] for r in rs) - (n - 2) < N:
        fl.append('P2:count')
    if allinv and not capable[N]:
        fl.append('V1:nocovmod')
    if sigcap is not None and all(r != 0 for r in rs):
        sig = tuple(sorted(tab['orders'][r] for r in rs))
        if sig not in sigcap.get(N, {}):
            fl.append('V2:sigcap')
    return fl

# ------------------------------------------------- exponent classification

def build_exponent_map(N, g=2):
    """class value -> exponent in Z_m (m=(N-1)/2), generator cls(g).
    Asserts that cls(g) really generates the class group."""
    m = (N - 1) // 2
    exp = {}
    val = 1
    for t in range(N - 1):
        c = val if val <= N - val else N - val
        exp.setdefault(c, t % m)
        val = val * g % N
    assert len(exp) == m, "cls(2) does not generate C_m at N=%d" % N
    return m, exp

def covers_exp(M, S, m):
    u = set()
    for e in M:
        for s in S:
            u.add((e + s) % m)
    return len(u) == m

def canon_multiset(M, m):
    mn = min(M)
    return tuple(sorted((x - mn) % m for x in M))

def canon_class(M, m):
    """True translate-class canonical form on the CYCLIC group Z_m:
    rotate each distinct element to 0, take the lexicographic minimum.
    (A 4-element class has up to 4 contains-0 representatives — 'subtract
    the min' alone does NOT normalize a cyclic translate.)"""
    return min(tuple(sorted((x - e) % m for x in M))
               for e in set(M))

def negation_class(M, m):
    """The translate class of the negated multiset (NOT a symmetry — a
    diagnostic: negation maps covering classes to usually-non-covering
    classes because B_{-w} = B_w, so -E is genuinely a different tuple)."""
    return canon_class([-x % m for x in M], m)

def classify_prime(N, T=6, verbose=True):
    """Full classification of unit 4-coverings at prime N (T=6)."""
    m, exp = build_exponent_map(N)
    h = (N - 1) // T
    S = tuple(sorted({exp[j] for j in range(1, h + 1)}))
    assert len(S) == h
    cover = []
    ncanon = 0
    for M in combinations_with_replacement(range(m), 4):
        if M[0] != 0:
            continue
        ncanon += 1
        if covers_exp(M, S, m):
            cover.append(M)
    cover_set = set(cover)
    if verbose:
        print("  N=%d: m=%d, h=%d, S exponents = %s" % (N, m, h, S))
        print("       canonical 4-multisets enumerated: %d; COVERING: %d"
              % (ncanon, len(cover)))
    return dict(m=m, h=h, S=S, exp=exp, cover=cover, cover_set=cover_set)

def residue_to_exponents(tup, N, exp):
    return tuple(sorted(exp[cls_inv(w, N)] for w in tup))

# ------------------------------------------------------------ corpus run

def corpus_run(n, VMAX, T, tabs, capable, sigcap=None, open_cap=30):
    k = n - 1
    total = 0
    closed = Counter()
    jgon_plain = Counter()
    pairstats = Counter()
    cert_hist = Counter()
    ground_fail = []
    open_sets = []
    open_pair_stats = Counter()
    all_unflagged = Counter()
    p1_witness_fail = 0
    m4_mismatch = 0
    open_plain = 0
    danger_pairs = Counter()
    missed1937 = 0   # self-check: unflagged allinv pairs at 19/37 (must be 0)
    rng = random.Random(7)
    for V in combinations(range(1, VMAX + 1), n):
        g = 0
        for x in V:
            g = gcd(g, x)
        if g != 1:
            continue
        total += 1
        certs = 0
        got = {'s': False, 'f': False, 'v': False, 'j': False}
        odetail = []
        set_unflagged = []
        for (p, q) in combinations(range(n), 2):
            N = V[p] + V[q]
            tab = tabs[N]
            others = [V[i] for i in range(n) if i != p and i != q]
            eff = (V[p],) + tuple(others)
            rs = tuple(w % N for w in eff)
            mm = tab['masks'][rs[0]]
            for r in rs[1:]:
                mm |= tab['masks'][r]
            cert = (mm != tab['full'])
            if not cert:
                continue
            certs += 1
            fl = battery_flags(N, rs, n, T, tabs, capable, sigcap)
            allinv = all(tab['invs'][r] for r in rs)
            if N in RIGID_PRIMES:
                danger_pairs[(N, allinv)] += 1
            for f in fl:
                pairstats[f] += 1
            for f in fl:
                if f.startswith('P1:jgon'):
                    j = int(f[7:])
                    if (mm >> (N // j)) & 1:
                        p1_witness_fail += 1
            if any(f.startswith(('P1', 'P2', 'P4')) for f in fl):
                got['s'] = True
            if any(not f.startswith('V') for f in fl):
                got['f'] = True
            if any(f.startswith('V') for f in fl):
                got['v'] = True
            if any(f.startswith('P1') for f in fl):
                got['j'] = True
            if not fl:
                sig = tuple(sorted(tab['orders'][r] for r in rs))
                key = (N, allinv, capable[N] if allinv else None, sig)
                set_unflagged.append(key)
                all_unflagged[key] += 1
                if allinv and N in (19, 37):
                    missed1937 += 1
                if len(odetail) < 4:
                    odetail.append((V[p], V[q], N, rs, sig))
            if rng.random() < 0.002:
                best = direct_grid_max(N, eff)
                if (T * best >= N) != cert:
                    m4_mismatch += 1
        if certs == 0:
            ground_fail.append(V)
        cert_hist[certs] += 1
        jgon_plain['jgon' if got['j'] else 'plain'] += 1
        if got['s']:
            closed['strict'] += 1
        elif got['f']:
            closed['P5only'] += 1
        elif got['v']:
            closed['Vonly'] += 1
        else:
            closed['OPEN'] += 1
            for key in set_unflagged:
                open_pair_stats[key] += 1
            if not got['j']:
                open_plain += 1
            if len(open_sets) < open_cap:
                open_sets.append((V, odetail))
    return dict(total=total, closed=closed, jgon_plain=jgon_plain,
                pairstats=pairstats, cert_hist=cert_hist,
                ground_fail=ground_fail, open_sets=open_sets,
                open_pair_stats=open_pair_stats, all_unflagged=all_unflagged,
                open_plain=open_plain, danger_pairs=danger_pairs,
                missed1937=missed1937,
                p1_witness_fail=p1_witness_fail, m4_mismatch=m4_mismatch)

def direct_grid_max(N, eff):
    best = 0
    for k in range(1, N):
        m = N
        for w in eff:
            r = (w * k) % N
            d = r if r <= N - r else N - r
            if d < m:
                m = d
        if m > best:
            best = m
    return best

def report(res, n, VMAX, tag):
    t = res['total']
    c = res['closed']
    strict = c['strict']
    full = c['strict'] + c['P5only']
    anyv = full + c['Vonly']
    print("\n---- corpus %s (n=%d, v<=%d, %d sets) [AUGMENTED battery] ----"
          % (tag, n, VMAX, t))
    print("  closed by PROVED ports only (P1+P2+P4):   %6d  (%.2f%%)"
          % (strict, 100.0 * strict / t))
    print("  closed by PROVED incl. new P5 (D3):        %6d  (%.2f%%)"
          % (full, 100.0 * full / t))
    print("  closed by PROVED+VERIFIED (+V1/V2):        %6d  (%.2f%%)"
          % (anyv, 100.0 * anyv / t))
    print("  OPEN:                                      %6d  (%.2f%%)"
          % (c['OPEN'], 100.0 * c['OPEN'] / t))
    print("  j-gon/plain (any-pair) split: %s" % dict(res['jgon_plain']))
    print("  per-flag pair counts: %s"
          % dict(sorted(res['pairstats'].items())))
    print("  rigid-prime certifying pairs (N,allinv)->count: %s"
          % dict(sorted(res['danger_pairs'].items(), key=str)))
    print("  SELF-CHECK unflagged allinv pairs at 19/37 (must be 0): %d"
          % res['missed1937'])
    print("  ground-truth failures: %d" % len(res['ground_fail']))
    print("  soundness: P1 witness fails %d, m4 mismatches %d"
          % (res['p1_witness_fail'], res['m4_mismatch']))
    return strict, full, anyv, c['OPEN']

def unflagged_decomposition(res, label):
    au = res['all_unflagged']
    tot = sum(au.values())
    by = Counter()
    for (N, allinv, cap, sig), c in au.items():
        if allinv:
            by['allinv @ capable %d' % N] += c
        elif N >= 48:
            by['kernel @ new composite N>=48'] += c
        else:
            by['kernel @ N<=47'] += c
    print("  [%s] unflagged certifying pairs corpus-wide: %d" % (label, tot))
    for k, v in by.most_common():
        print("      %-34s %7d" % (k, v))
    return tot

# ------------------------------------------------------------------- main

def main():
    t0 = time.time()
    print("=" * 72)
    print("N7 — CLASSIFICATION OF THE RIGID PRIMES 19 AND 37 (K19 / K37)")
    print("     + augmented-battery corpus re-measurement")
    print("=" * 72)

    tabs5 = {N: build_tables(N, 6) for N in range(3, 80)}
    cov5 = {N: capable_units(N, tabs5[N], 4) for N in range(3, 80)}
    cap5 = {N: bool(v) for N, v in cov5.items()}
    assert sorted(N for N in range(3, 80) if cap5[N]) == \
        sorted([7, 13, 17, 19, 37] + [N for N in range(48, 80) if cap5[N]])

    # ================= Part 1: the classifications =================
    for N, committed_count in ((19, 64), (37, 32)):
        print("\n===== K%d classification =====" % N)
        cl = classify_prime(N)
        m, S, exp = cl['m'], cl['S'], cl['exp']
        tab = tabs5[N]
        cov = cov5[N]
        cov_sb = capable_setbased(N)
        print("  [check] residue-level coverings: mask %d, set-based %d, "
              "committed %d" % (len(cov), len(cov_sb), committed_count))
        assert len(cov) == len(cov_sb) == committed_count

        # (3) residue coverings <-> exponent classification, both ways
        cov_canon = Counter()
        for tup in cov:
            E = residue_to_exponents(tup, N, exp)
            c = canon_multiset(E, m)
            assert c in cl['cover_set'], \
                "residue covering outside classification: %s -> %s" % (tup, c)
            cov_canon[c] += 1
        realized = set(cov_canon)
        assert realized == cl['cover_set'], \
            "classification/realization mismatch at N=%d" % N
        # multiplicity structure: distinct-element coverings realize 8 each
        mult = Counter()
        for c, cnt in cov_canon.items():
            dist = len(set(c))
            mult[(dist, cnt)] += 1
        print("  [check] all %d residue coverings map into the "
              "classification; all %d classified canonical multisets "
              "realized" % (len(cov), len(cl['cover_set'])))
        print("         realization multiplicity (distinct elems, count): %s"
              % dict(sorted(mult.items())))

        # (4)+(5) predicate and orbit-list exactness over ALL unit multisets
        units = [w for w in range(1, N) if tab['invs'][w]]
        mism_pred = 0
        mism_orbit = 0
        nall = 0
        for rs in combinations_with_replacement(units, 4):
            nall += 1
            mm = 0
            for r in rs:
                mm |= tab['masks'][r]
            covering = (mm == tab['full'])
            # predicate (class union < m)
            h = (N - 1) // 6
            covered = set()
            for r in rs:
                X = cls_inv(r, N)
                for j in range(1, h + 1):
                    covered.add(cls(X * j, N))
            pred_noncover = len(covered) < m
            if covering == pred_noncover:
                mism_pred += 1
            # orbit-list characterization
            E = tuple(sorted(exp[cls_inv(r, N)] for r in rs))
            in_list = canon_multiset(E, m) in cl['cover_set']
            if covering != in_list:
                mism_orbit += 1
        print("  [check] over ALL %d unit 4-multisets: predicate mismatches "
              "%d, orbit-list mismatches %d" % (nall, mism_pred, mism_orbit))
        assert mism_pred == 0 and mism_orbit == 0

        # ---- print the classification (the theorem content)
        classes = {}
        for M in cl['cover']:
            classes.setdefault(canon_class(M, m), []).append(M)
        cover_classes = set(classes)
        print("  COVERING translate-CLASSES of Z_%d: %d"
              % (m, len(classes)))
        for c, reps in sorted(classes.items()):
            gaps = [(c[(i + 1) % 4] - c[i]) % m for i in range(4)]
            negc = negation_class(c, m)
            print("      class %-14s gaps %-14s reps %d  "
                  "negation-class covering: %s"
                  % (str(c), str(gaps), len(reps), negc in cover_classes))
            for M in reps:
                print("           rep %s" % (M,))
        # sanity: every covering contains-0 multiset belongs to a class whose
        # canon_class is itself in the list, and reps partition the list
        assert sum(len(r) for r in classes.values()) == len(cl['cover'])
        for M in cl['cover']:
            assert canon_class(M, m) in classes
        print("      [check] %d contains-0 representatives partition into "
              "%d translate classes" % (len(cl['cover']), len(classes)))
        print("      (elapsed %.1fs)" % (time.time() - t0))

    # ================= Part 2: augmented battery =================
    print("\n===== battery soundness with P4 at {7,13,17,19,37} =====")
    # classification exactness at all five moduli
    for N in (7, 13, 17, 19, 37):
        tab = tabs5[N]
        masks, full = tab['masks'], tab['full']
        units = [w for w in range(1, N) if tab['invs'][w]]
        mism = 0
        for rs in combinations_with_replacement(units, 4):
            mm = 0
            for r in rs:
                mm |= masks[r]
            if (mm != full) != (flag_classification(N, rs, 6) is not None):
                mism += 1
        print("  [check] P4 predicate<=>mask at N=%d: %d mismatches "
              "(%d multisets)" % (N, mism, len(units) * (len(units) + 1) *
                                  (len(units) + 2) * (len(units) + 3) // 24))
        assert mism == 0

    t1 = time.time()
    print("\n[sigcap] building order-signature capability maps, N=3..79...")
    sigcap = {}
    for N in range(3, 80):
        masks, full, orders = tabs5[N]['masks'], tabs5[N]['full'], \
            tabs5[N]['orders']
        cap = {}
        res = list(range(1, N))
        idx = list(range(len(res)))
        for i in idx:
            mi = masks[res[i]]
            oi = orders[res[i]]
            for jj in idx[i:]:
                mij = mi | masks[res[jj]]
                for kk in idx[jj:]:
                    mijk = mij | masks[res[kk]]
                    for ll in idx[kk:]:
                        if mijk | masks[res[ll]] == full:
                            sig = tuple(sorted((oi, orders[res[jj]],
                                                orders[res[kk]],
                                                orders[res[ll]])))
                            if sig not in cap:
                                cap[sig] = (res[i], res[jj], res[kk],
                                            res[ll])
        sigcap[N] = cap
    print("      (elapsed %.1fs)" % (time.time() - t1))

    # flag => cert sweeps (exhaustive where P4 now fires, random elsewhere)
    v5a, c5a = soundness_sweep_range(tabs5, cap5, 5, 6, range(3, 32),
                                     sigcap=sigcap)
    v5b, c5b = soundness_sweep_range(tabs5, cap5, 5, 6, [37],
                                      exhaustive=True, sigcap=sigcap)
    v5c, c5c = soundness_sweep_range(tabs5, cap5, 5, 6, range(32, 80),
                                     exhaustive=False, n_random=4000,
                                     sigcap=sigcap)
    print("  [check] flag=>cert: 3..31 exhaustive %d/%d viol; N=37 "
          "exhaustive %d/%d viol; 32..79 random %d/%d viol"
          % (len(v5a), c5a, len(v5b), c5b, len(v5c), c5c))
    assert not v5a and not v5b and not v5c

    # ================= Part 3: augmented corpora =================
    print("\n===== corpora with the augmented battery =====")
    res24 = corpus_run(5, 24, 6, tabs5, cap5, sigcap=sigcap)
    s24, f24, v24, o24 = report(res24, 5, 24, "V=24")
    assert res24['total'] == 41656
    unflagged_decomposition(res24, "V=24")

    res32 = corpus_run(5, 32, 6, tabs5, cap5, sigcap=sigcap)
    s32, f32, v32, o32 = report(res32, 5, 32, "V=32")
    unflagged_decomposition(res32, "V=32")

    res40 = corpus_run(5, 40, 6, tabs5, cap5, sigcap=sigcap)
    s40, f40, v40, o40 = report(res40, 5, 40, "V=40")
    unflagged_decomposition(res40, "V=40")

    print("\n" + "=" * 72)
    print("===== AUGMENTED TREND (P4 at {7,13,17,19,37}) =====")
    print("=" * 72)
    print("  V    sets    ports      +D3      +V(any)   OPEN")
    for VV, r in ((24, res24), (32, res32), (40, res40)):
        t = r['total']
        c = r['closed']
        st = c['strict']
        fu = st + c['P5only']
        av = fu + c['Vonly']
        print("  %2d  %6d  %6d %6.2f%%  %6.2f%%  %6.2f%%  %4d"
              % (VV, t, st, 100.0 * st / t, 100.0 * fu / t,
                 100.0 * av / t, c['OPEN']))
    print("\n  committed Phase-1 (same battery minus K19/K37): "
          "V=24: 35778/36362; see scripts/n6_run.log for V=32/40.")
    print("  total elapsed: %.1fs" % (time.time() - t0))

def soundness_sweep_range(tabs, capable, n, T, Nrange, exhaustive=True,
                          n_random=0, seed=1, sigcap=None):
    k = n - 1
    viol = []
    checked = 0
    rng = random.Random(seed)
    for N in Nrange:
        tab = tabs[N]
        masks, full = tab['masks'], tab['full']
        if exhaustive:
            for rs in combinations_with_replacement(range(N), k):
                mm = 0
                for r in rs:
                    mm |= masks[r]
                fl = battery_flags(N, rs, n, T, tabs, capable, sigcap)
                if fl and mm == full:
                    viol.append((N, rs, fl))
                checked += 1
        if n_random:
            for _ in range(n_random):
                rs = tuple(sorted(rng.randrange(N) for _ in range(k)))
                mm = 0
                for r in rs:
                    mm |= masks[r]
                fl = battery_flags(N, rs, n, T, tabs, capable, sigcap)
                if fl and mm == full:
                    viol.append((N, rs, fl))
                checked += 1
    return viol, checked

if __name__ == '__main__':
    main()
